


--SELECT fname + '  ' + minit + ' ' + lname    AS NAME FROM EMPLOYEE
INNER JOIN WORKS_ON
ON employee.SSN=WORKS_ON.ESSN


SELECT lname  FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON employee.SSN=DEPARTMENT.MGRSSN
left JOIN DEPENDENT
ON EMPLOYEE.SSN=DEPENDENT.ESSN
WHERE DEPENDENT.ESSN IS NULL


SELECT fname + '  ' + minit + ' ' + lname    AS NAME  FROM EMPLOYEE
LEFT JOIN WORKS_ON
ON employee.SSN=WORKS_ON.ESSN
WHERE WORKS_ON.ESSN IS null



SELECT fname + '  ' + minit + ' ' + lname AS NAME , ssn, avg (salary)  AS OUTPUT FROM EMPLOYEE
GROUP BY fname,minit,lname, ssn, salary
HAVING avg(salary)>
--ORDER BY salary DESC



SELECT fname , minit, lname,ssn,bdate,address,sex, dno, salary FROM EMPLOYEE
GROUP BY fname , minit, lname,ssn,bdate,address,sex, dno, salary
HAVING EMPLOYEE.SALARY > (SELECT avg(EMPLOYEE.SALARY ) FROM EMPLOYEE )
ORDER BY salary DESC



SELECT fname , dno, salary FROM EMPLOYEE 
GROUP BY fname, dno, salary
HAVING EMPLOYEE.SALARY > (SELECT avg(EMPLOYEE.SALARY )  FROM EMPLOYEE GROUP BY dno )

ORDER BY salary asc


SELECT fname ,dno,EMPLOYEE.SALARY  FROM  EMPLOYEE
where EMPLOYEE.SALARY > (SELECT avg(EMPLOYEE.SALARY) FROM EMPLOYEE GROUP BY dno)
GROUP BY fname, employee.SALARY,dno 
ORDER BY salary asc


SELECT fname ,dno,avg(EMPLOYEE.SALARY) FROM EMPLOYEE GROUP BY dno,fname




SELECT ssn, fname + '  ' + minit + ' ' + lname AS NAME , address, WORKS_ON.ESSN,DEPARTMENT.DNUMBER  FROM EMPLOYEE
INNER JOIN WORKS_ON
ON EMPLOYEE.SSN=WORKS_ON.ESSN
inner JOIN PROJECT
ON WORKS_ON.PNO=PROJECT.PNUMBER

INNER JOIN DEPARTMENT
ON PROJECT.DNUM=DEPARTMENT.DNUMBER

INNER JOIN DEPT_LOCATIONS
ON DEPARTMENT.DNUMBER=DEPT_LOCATIONS.DNUMBER

WHERE PROJECT.PLOCATION='Houston' AND DEPT_LOCATIONS 
--AND  DEPT_LOCATIONS.DLOCATION = 'Houston'



UPDATE EMPLOYEE
SET DNO=1
WHERE SSN=66666



INSERT INTO EMPLOYEE
VALUES ('Jansen', 'L', 'Ibabao', 99999, '1975/08/04', 'Silang', 'Female', 45000,NULL,  5)



