SELECT FNAME, MINIT, LNAME,SSN,BDATE, ADDRESS,SEX,SALARY,SUPERSSN,DNO INTO EMP1 FROM EMPLOYEE





CREATE VIEW    AS VIEWEMP FROM EMP1
INNER JOIN ON JOBS
ON EMP1.JobNum =JOBS.JobNum

SELECT AGE, LEVEL FROM STUDENT
INNER JOIN ENROLLED
ON STUDENT.SNUM=ENROLLED.SNUM






-------------------------------EMP1
ALTER TABLE EMP1 ADD JobNum INT 

ALTER TABLE EMP1 ADD PRIMARY KEY (SSN)

ALTER TABLE EMP1 ADD FOREIGN KEY (DNO) REFERENCES DEPARTMENT (dnumber)
ALTER TABLE EMP1 ADD FOREIGN KEY (JobNum) REFERENCES JOBS (JobNum)



INSERT INTO EMP1 (Jobnum)
VALUES (101)
UPDATE EMP1
SET jobnum=10
WHERE ssn=22222

-------------------------------JOBS


CREATE TABLE JOBS
(
JobNum INT,
JobName VARCHAR (20)

PRIMARY KEY (Job num)
)


INSERT INTO JOBS (jobnum, jobname)
VALUES (106 , 'Finance Sprvsr')


DELETE FROM jobs WHERE JobName ='System Analyst'


-----------------------1) VIEWEMP

CREATE VIEW  VIEWEMP AS SELECT FNAME, MINIT,LNAME, SALARY, DNO, EMP1.JOBNUM  FROM EMP1
INNER JOIN JOBS
ON EMP1.JobNum=JOBS.JobNUM



-----------------------2) DEPTSUM
CREATE VIEW  DEPTSUM AS SELECT EMP1.DNO AS 'DEPARTMENT' ,   SUM(EMP1.SALARY) AS 'SUMSAL' FROM EMP1 
INNER JOIN DEPARTMENT
ON EMP1.DNO=DEPARTMENT.DNUMBER
GROUP BY EMP1.DNO



-----------------------3) BOSS


CREATE VIEW  BOSS1 AS SELECT EMP1.FNAME + ' ' + EMP1.MINIT + ' ' +  LNAME  AS EmplName, EMP1.SSN AS EmplID, EMP1.SUPERSSN
AS  MANAGER FROM EMP1 
INNER JOIN DEPARTMENT
ON EMP1.DNO=DEPARTMENT.DNUMBER
GROUP BY EMP1.FNAME + ' ' + EMP1.MINIT + ' ' +  LNAME ,EMP1.SSN,  EMP1.SUPERSSN


CREATE VIEW  BOSS AS SELECT EMP1.FNAME + ' ' + EMP1.MINIT + ' ' +  LNAME  AS EmplName, EMP1.SSN AS EmplID, EMP1.SUPERSSN
AS  MANAGER   FROM EMP1 
INNER JOIN DEPARTMENT
ON EMP1.SUPERSSN=DEPARTMENT.MGRSSN
WHERE EMP1.SUPERSSN =EMP1.SSN

SELECT CONVERT(VARCHAR(201), EMP1.SUPERSSN)(SELECT SSN FROM EMP1)
 FROM EMP1 
 
 
 
 SELECT STR(EMPLOYEE.SSN)  + ' ' +  LNAME AS EMPL , EMPLOYEE.SUPERSSN  AS MANAGER FROM EMPLOYEE
 INNER JOIN DEPARTMENT
 ON EMPLOYEE.DNO= DEPARTMENT.DNUMBER
 
 
SELECT employee.SSN, EMPLOYEE.fname + ' ' +  EMPLOYEE.lname AS EMPL_NAME, DEPARTMENT.mgrssn AS MANAGER FROM DEPARTMENT
inner JOIN EMPLOYEE
ON DEPARTMENT.MGRSSN =EMPLOYEE.SUPERSSN




SELECT SSN, FNAME , DNO, department.MGRSSN  FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON employee.DNO=DEPARTMENT.DNUMBER


UPDATE EMPLOYEE
SET SUPERSSN=11111
WHERE SSN=88888
 
 ALTER TABLE DEPT DROP COLUMN mgrstartdate
 
 ALTER TABLE DEPT DROP CONSTRAINT PK__DEPT__F5A986061F98B2C1
 
 
ALTER TABLE DEPT ALTER COLUMN  MGRNAME VARCHAR (10)


ALTER TABLE DEPT ADD PRIMARY KEY (MGRSSN)

ALTER TABLE DEPT ALTER COLUMN MGRSSN INT NOT NULL


ALTER TABLE EMP1 ADD FOREIGN KEY (dno) REFERENCES DEPT (mgrssn)


TRUNCATE TABLE dept
 --------------------------------SALES1
 
 CREATE VIEW SALES1 AS SELECT  FNAME, MINIT,LNAME,SSN,BDATE,SEX,SUPERSSN,DNO  FROM EMPLOYEE  
 
 WHERE DNO=30
 
 --------------------------------SALES2

CREATE VIEW SALES2 AS SELECT  FNAME, MINIT,LNAME,SSN,BDATE,SEX,SUPERSSN,DEPARTMENT.DNAME  FROM EMPLOYEE  
INNER JOIN DEPARTMENT
ON EMPLOYEE.DNO= DEPARTMENT.DNUMBER

-----------------------------------------------

DELETE VIEWEMP VIEWEMP

UPDATE DEPARTMENT 
SET MGRSSN=10100
WHERE DNUMBER=30



INSERT INTO EMPLOYEE
VALUES ('Aan','L', 'Omanito',10101 , 1990/02/05, 'Trece', 'Female', 20000, 10100, 30)

 INSERT INTO DEPARTMENT (DNAME,DNUMBER , MGRSSN,MGRSTARTDATE )
VALUES ('SMD', 30,null, '2000/03/05')

 
ALTER TABLE emp1 ADD FOREIGN KEY (superssn) REFERENCES EMP1(ssn)


CREATE VIEW BOSS AS 
SELECT ssn, emp1.FNAME + ' '  + minit + ' ' + lname AS EMPL_NAME , mgrname AS MANAGER FROM EMP1
INNER JOIN dept
ON EMP1.DNO = dept.MGRSSN